update to setup instructions
ocean-tracking-network/node-manager-training pull request #57
Opened 2024-11-06 13:51 UTC by bmanjones

Added steps to use miniforge instead of the older miniconda instructions. Issue https://github.com/ocean-tracking-network/node-manager-training/issues/45

2024-11-06 15:00 UTC, jdpye approved these changes
good update by me.

2024-11-06 15:52 UTC, CaitlinBate requested changes

2024-11-06 15:52 UTC, CaitlinBate commented on _episodes/03_Setup_and_Installing_Needed_Software.md
> +- **MAC/WINDOWS/LINUX**: Open your terminal, and navigate to your ipython-utilities directory, using `cd /paht/to/ipython-utilities`. Then, run the commands:
path is spelled wrong

2024-11-06 15:52 UTC, CaitlinBate commented on _episodes/03_Setup_and_Installing_Needed_Software.md
> +* https://code.visualstudio.com/
this is already down in line 125 - can we remove from one of the places? and to make the link render properly I think we need to do [link](link)

2024-11-06 15:52 UTC, CaitlinBate commented on _episodes/03_Setup_and_Installing_Needed_Software.md
> +  - Check the option to Add Miniforge3 to my PATH environment variable.
make " Add Miniforge3 to my PATH environment variable." bold pls - this is an important step haha

2024-11-06 15:52 UTC, CaitlinBate commented on _episodes/03_Setup_and_Installing_Needed_Software.md
> + **Miniforge Windows** - https://conda-forge.org/miniforge/
i think the link needs to be [link](link) to make it clickable on the site

2024-11-06 15:52 UTC, CaitlinBate commented on _episodes/03_Setup_and_Installing_Needed_Software.md
> +   - download Shell script (.sh) file from https://conda-forge.org/miniforge/
i think the link needs to be [link](link}

2024-11-19 20:37 UTC, CaitlinBate approved these changes

2024-11-19 20:38 UTC, CaitlinBate commented
this can be merged once conflicts are inspected @bmanjones @jackVanish

2024-11-20 13:58 UTC, merged