Made changes in line with ticket 58.
ocean-tracking-network/node-manager-training pull request #70
Opened 2024-11-06 19:34 UTC by jackVanish

- Copied the issue template from gitlab
- added a line clarifying that the input options are in two different cells
- fixed typo in 'skip to verification' section
- updated definition for 'shortname' (example may also need to change).

2024-11-12 18:22 UTC, CaitlinBate requested changes
made some comments that i think need team discussion

2024-11-12 18:22 UTC, CaitlinBate commented on _episodes/05_project_metadata.md
> -- [ ] - NAME pass issue to OTN DAQ staff
i have some thoughts about the "OTN only" parts of the checklist. 

1) loan: OTN does this early on but other nodes need to assign to OTN to check if its a loan at the end. not sure how to capture both of these?
2) plone: there are multiple nodes which use Plone now, I think those shouldn't say [OTN only] but say [Plone-users only] or something?
3) emailing PIs: each node will have its own snippet/template, the OTN one is not universal

also: all instances should say "repository" not "repo"

2024-11-12 18:22 UTC, CaitlinBate commented on _episodes/05_project_metadata.md
> +1. Shortname: usually the project code, which will be used as the name of the Data Portal folder. ex: `OTN Blue Sharks`.
shortname is not the same as project code, your example is correct tho! "usually the nickname for the project" or "usually a summarized title for the project"??

2024-11-14 17:11 UTC, jackVanish commented on _episodes/05_project_metadata.md
> +1. Shortname: usually the project code, which will be used as the name of the Data Portal folder. ex: `OTN Blue Sharks`.
Right on, changed it to 'usually a summarised version of the project title'.

2024-11-18 19:20 UTC, slandovs commented on _episodes/05_project_metadata.md
> -- [ ] - NAME pass issue to OTN DAQ staff
1. Is there a reason we have it earlier on ours? I wonder if it makes the most sense to just move it down lower in the list for ourselves?
2. I agree re 'Plone-users only'
3. I agree - emailing the PIs is node specific

I made some changes in lessons that said "info" and changed it to "information" - similar to the repository/repo change Caitlin mentioned!

2024-11-18 19:31 UTC, CaitlinBate commented on _episodes/05_project_metadata.md
> -- [ ] - NAME pass issue to OTN DAQ staff
for 1. i think its early in the checklist because it appears in the notebook at that point (in the create proj notebook, before moving to the plone notebook). but for other nodes, they skip this, do plone, then pass to OTN for verification and loan updating :P 

I thnk workflow should be -- NODE-DAQ loads, incl plone steps, then OTNDAQ checks loan, then OTNDB verifies and closes. we could make ours match this since the loan info cells ALSO exist in the plone notebook soooooo we can do em at the end

2024-11-19 14:50 UTC, CaitlinBate commented on _episodes/05_project_metadata.md
> -- [ ] - NAME pass issue to OTN DAQ staff
the answer
- use node-agnostic templates
- add a note or two about "some nodes have custom templates"
- ioython should be the "general" templates to use - CB to check

2024-11-25 17:33 UTC, CaitlinBate commented
checklist to use

Project Metadata
- [ ] - NAME add label *'loading records'*
- [ ] - NAME define type of project  **select here one of Data, Deployment, Tracker**
- [ ] - NAME create schema and project records (`Creating and Updating project metadata` notebook)
- [ ] - NAME add project contact information (`Creating and Updating project metadata` notebook)
- [ ] - NAME add scientificnames (`Creating and Updating project metadata` notebook)
- [ ] - NAME verify all of above (`Creating and Updating project metadata` notebook)
- [ ] - NAME [Plone-users only] create new project repository users (`Create Plone Folders and Add Users` notebook)
- [ ] - NAME [Plone-users only] create project repository folder (`Create Plone Folders and Add Users` notebook)
- [ ] - NAME [Plone-users only] add project repository users to folder (`Create Plone Folders and Add Users` notebook)
- [ ] - NAME [Plone-users only] access project repository double-check project repository creation and user access 
- [ ] - NAME add project metadata file to relevant project folder (Plone site, Research Workspace etc)
- [ ] - NAME email notification of updated metadata file to PI and individual who submitted
- [ ] - NAME send onboarding email to all contacts
- [ ] - NAME label issue with *'Verify'*
- [ ] - NAME pass issue to OTN DAQ staff
- [ ] - NAME [OTN only] manually identify if this is a loan, if so add record to otnunit.obis.loan_tracking (`Creating and Updating project metadata` notebook)
- [ ] - NAME [OTN only] if this is a loan, update links for PMO
- [ ] - NAME pass issue to OTN analyst for final verification
- [ ] - NAME verify project in database


**project metadata txt file**

2024-11-25 17:35 UTC, CaitlinBate commented
please also a note somewhere in this lesson saying: "OTN has a template we use for our onboarding emails. It is recommended that you create a template for your Node which includes relevant reporting instructions."

this can be 1) right after the checklist or 2) later down in the notebook when the "email PIs" Tasklist checkpoint occurs

2024-11-25 17:36 UTC, CaitlinBate commented on _episodes/05_project_metadata.md
> -- [ ] - NAME pass issue to OTN DAQ staff
update - ipython templates are old and bad. i have assigned myself the task of updating them to match these training lessons

2024-11-25 18:07 UTC, CaitlinBate approved these changes

2024-11-25 18:08 UTC, merged