Made changes in line with ticket 63.
ocean-tracking-network/node-manager-training pull request #73
Opened 2024-11-13 13:19 UTC by jackVanish

A few of the supplementary notebook fixes that can be addressed so far. 

- Linked to the fathom convert notebook.
- Removed outdated glider notebook sections
- Changed the push schedule to be generic.

2024-11-13 14:17 UTC, CaitlinBate requested changes

2024-11-13 14:17 UTC, CaitlinBate commented on _episodes/10_The Push.md
>  With the increased number of Nodes joining the Pushes, we are announcing the schedule for the next year. Please prepare in advance and mark your calendars.
prob delete this line too?

2024-11-13 14:17 UTC, CaitlinBate commented on _episodes/09_Supplementary notebooks.md
> +## [convert - Fathom (vdat) Export - VRL to CSV](http://localhost:8888/notebooks/convert%20-%20Fathom%20(vdat)%20Export%20-%20VRL%20to%20CSV.ipynb)
the ask was to "Link to the "convert - fathom" notebook in the detections module." so I think we wanted the Detections lesson to link to the instructions which are found in this lesson. not linking to actual notebooks? i think

2024-11-14 17:23 UTC, jackVanish commented on _episodes/10_The Push.md
>  With the increased number of Nodes joining the Pushes, we are announcing the schedule for the next year. Please prepare in advance and mark your calendars.
Line deleted.

2024-11-14 17:24 UTC, jackVanish commented on _episodes/09_Supplementary notebooks.md
> +## [convert - Fathom (vdat) Export - VRL to CSV](http://localhost:8888/notebooks/convert%20-%20Fathom%20(vdat)%20Export%20-%20VRL%20to%20CSV.ipynb)
Link changed to go to the lesson (and anchor tag added to jump right to that spot on the page).

2024-11-14 17:24 UTC, jackVanish commented
Changes made, if it's all copacetic with @CaitlinBate I will merge it.

2024-11-14 17:38 UTC, CaitlinBate requested changes
almost there! once the last thing is done, it can be merged

2024-11-14 17:38 UTC, CaitlinBate commented on _episodes/08_Detections.md
> +# <a name="convertToCSV"></a>Convert to CSV
i think this link needs go to in line 84 (where it says `- `convert - Fathom (vdat) Export - VRL to CSV` Nodebook`)

2024-11-14 17:45 UTC, jackVanish commented on _episodes/08_Detections.md
> +# <a name="convertToCSV"></a>Convert to CSV
I'm not sure about that- I think it should link to the header. The two places are pretty close so it won't make much difference, and I think having the header be visible when you drop in makes it clearer where the link has taken you. A person who's followed the link thru from the supplemental notebooks section already knows what they're looking for and will find the spot in the list that they want pretty quickly. 

That's just my two cents tho, if you still want it moved I'll move it, but that's my reasoning.

2024-11-14 17:51 UTC, CaitlinBate commented on _episodes/08_Detections.md
> +# <a name="convertToCSV"></a>Convert to CSV
for someone who is learning/taking the Detections module (this file), there are multiple ways to convert detections to CSV, only one of which (line 84) is referring to the supplementary notebook.

better not to link at the top since the rest of the options (using VUE, using LOtek software... etc) have nothing to do w the `convert - Fathom (vdat) Export - VRL to CSV` notebook yah know?

I just want learners who are in the Detections lesson to get sent to the supplementary lesson to learn more about `convert - Fathom (vdat) Export - VRL to CSV` if this is the option they choose

2024-11-15 17:13 UTC, jackVanish commented on _episodes/08_Detections.md
> +# <a name="convertToCSV"></a>Convert to CSV
Okeydoke, I moved it.

2024-11-19 13:29 UTC, merged